using System.Timers;
using Microsoft.JSInterop;
using ThePlanningBord.Models;

namespace ThePlanningBord.Services
{
    public class BackgroundJobService : IDisposable
    {
        private readonly IInventoryService _inventoryService;
        private readonly IPurchaseOrderService _purchaseOrderService;
        private readonly IJSRuntime _jsRuntime;
        private readonly SmtpEmailService _smtpEmailService;
        private System.Timers.Timer? _timer;
        private bool _isRunning;

        public BackgroundJobService(
            IInventoryService inventoryService, 
            IPurchaseOrderService purchaseOrderService,
            IJSRuntime jsRuntime, 
            SmtpEmailService smtpEmailService)
        {
            _inventoryService = inventoryService;
            _purchaseOrderService = purchaseOrderService;
            _jsRuntime = jsRuntime;
            _smtpEmailService = smtpEmailService;
        }

        public void Start()
        {
            if (_isRunning) return;

            _timer = new System.Timers.Timer(60000); // Check every 1 minute
            _timer.Elapsed += async (sender, e) => await CheckInventory();
            _timer.AutoReset = true;
            _timer.Enabled = true;
            _isRunning = true;
        }

        private async Task CheckInventory()
        {
            try
            {
                var notificationsEnabledStr = await _jsRuntime.InvokeAsync<string>("getSetting", "notifications_enabled");
                if (!bool.TryParse(notificationsEnabledStr, out bool notificationsEnabled) || !notificationsEnabled)
                {
                    return;
                }

                // Fetch data
                var result = await _inventoryService.GetProductsAsync(null, 1, 10000); // Fetch all
                var products = result.Items;
                var lowStock = products.Where(p => p.CurrentQuantity <= p.MinimumQuantity).ToList();

                if (!lowStock.Any()) return;

                // Check for auto-order settings
                var emailEnabledStr = await _jsRuntime.InvokeAsync<string>("getSetting", "email_alerts_enabled");
                bool emailEnabled = bool.TryParse(emailEnabledStr, out bool eEnabled) && eEnabled;

                if (!emailEnabled)
                {
                    // Just notify admin locally if email is disabled
                    var message = $"Warning: {lowStock.Count} items are low on stock!";
                    await _jsRuntime.InvokeVoidAsync("notify", message);
                    return;
                }

                // Auto-Order Logic
                var suppliers = await _inventoryService.GetSuppliersAsync();
                var allPOs = await _purchaseOrderService.GetPurchaseOrdersAsync();
                var activePOs = allPOs.Where(po => po.Status != "Received" && po.Status != "Cancelled").ToList();

                var autoOrderedItems = new List<string>();
                var manualAttentionItems = new List<string>();

                var globalOrderEmail = await _jsRuntime.InvokeAsync<string>("getSetting", "global_order_email");

                foreach (var item in lowStock)
                {
                    // Check if already ordered
                    bool alreadyOrdered = activePOs.Any(po => po.Lines != null && po.Lines.Any(l => l.ProductId == item.Id));
                    if (alreadyOrdered) continue;

                    if (item.ReorderQuantity > 0 && !string.IsNullOrEmpty(item.SupplierName))
                    {
                        var supplier = suppliers.FirstOrDefault(s => s.Name.Equals(item.SupplierName, StringComparison.OrdinalIgnoreCase));
                        if (supplier != null)
                        {
                            // Determine target email: Supplier Order Email -> Global Order Email -> Supplier General Email
                            var targetEmail = !string.IsNullOrWhiteSpace(supplier.OrderEmail) ? supplier.OrderEmail : globalOrderEmail;
                            if (string.IsNullOrWhiteSpace(targetEmail)) targetEmail = supplier.Email;

                            if (!string.IsNullOrEmpty(targetEmail))
                            {
                                // Create PO
                                var po = new PurchaseOrder
                                {
                                    SupplierId = supplier.Id,
                                    Status = "Draft", // Will be updated to Sent after email? Or keep Draft for approval? User said "will be ordered". Let's say "Ordered".
                                    OrderDate = DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss"),
                                    TotalAmount = item.ReorderQuantity * item.UnitPrice, // Approx
                                    Notes = "Auto-generated by Low Stock System",
                                    Lines = new List<PurchaseOrderLine>
                                    {
                                        new PurchaseOrderLine
                                        {
                                            ProductId = item.Id,
                                            QuantityOrdered = item.ReorderQuantity,
                                            UnitPrice = item.UnitPrice,
                                            TotalPrice = item.ReorderQuantity * item.UnitPrice
                                        }
                                    }
                                };

                                try 
                                {
                                    await _purchaseOrderService.CreatePurchaseOrderAsync(po);
                                    
                                    // Send Email to Supplier
                                    var subject = $"Purchase Order: {item.Name}";
                                    var body = $"Dear {supplier.Name},\n\nPlease ship the following item:\n\n" +
                                               $"Product: {item.Name}\n" +
                                               $"SKU: {item.Sku}\n" +
                                               $"Quantity: {item.ReorderQuantity}\n\n" +
                                               $"Thank you,\nThe Planning Bord System";
                                    
                                    bool emailSent = await _smtpEmailService.SendEmailAsync(targetEmail, subject, body);
                                    
                                    if (emailSent)
                                    {
                                        autoOrderedItems.Add($"{item.Name} (Qty: {item.ReorderQuantity}) from {supplier.Name} (sent to {targetEmail})");
                                    }
                                    else
                                    {
                                        manualAttentionItems.Add($"{item.Name} (Email failed)");
                                    }
                                }
                                catch
                                {
                                    manualAttentionItems.Add($"{item.Name} (PO Creation failed)");
                                }
                            }
                            else
                            {
                                manualAttentionItems.Add($"{item.Name} (Missing Supplier Email)");
                            }
                        }
                        else
                        {
                             manualAttentionItems.Add($"{item.Name} (Supplier not found)");
                        }
                    }
                    else
                    {
                        manualAttentionItems.Add($"{item.Name} (No Reorder Qty/Supplier)");
                    }
                }

                // Notify Admin
                var adminEmail = await _jsRuntime.InvokeAsync<string>("getSetting", "admin_email");
                if (!string.IsNullOrEmpty(adminEmail) && (autoOrderedItems.Any() || manualAttentionItems.Any()))
                {
                    var sb = new System.Text.StringBuilder();
                    sb.AppendLine("Low Stock Report:");
                    
                    if (autoOrderedItems.Any())
                    {
                        sb.AppendLine("\nAuto-Ordered Items:");
                        foreach (var i in autoOrderedItems) sb.AppendLine($"- {i}");
                    }

                    if (manualAttentionItems.Any())
                    {
                        sb.AppendLine("\nRequires Manual Attention:");
                        foreach (var i in manualAttentionItems) sb.AppendLine($"- {i}");
                    }

                    await _smtpEmailService.SendEmailAsync(adminEmail, "Low Stock Auto-Order Report", sb.ToString());
                }
                
                if (autoOrderedItems.Any())
                {
                    await _jsRuntime.InvokeVoidAsync("notify", $"Auto-ordered {autoOrderedItems.Count} items.");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"BackgroundJobService Error: {ex.Message}");
            }
        }

        public void Dispose()
        {
            _timer?.Stop();
            _timer?.Dispose();
        }
    }
}
