---
name: Security Report
description: Report a security vulnerability
title: '[SECURITY] '
labels: ['security', 'high-priority']
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If you've discovered a security vulnerability, please DO NOT open a public issue.
        
        Instead, please email security@planningbord.com with details about the vulnerability.
        
        For non-critical security-related issues (like security enhancements), you can use this template.
  
  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern
      placeholder: A clear and concise description of the security issue...
    validations:
      required: true
  
  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: Describe the potential impact if this issue were exploited
      placeholder: What could happen if this issue is exploited?
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: If this is a reproducible vulnerability, provide steps
      placeholder: How can this issue be reproduced?
  
  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for how to mitigate this issue
      placeholder: How could this issue be fixed or mitigated?
  
  - type: checkboxes
    id: disclosure
    attributes:
      label: Disclosure
      description: Please confirm
      options:
        - label: I have not disclosed this issue publicly elsewhere
          required: true
        - label: I understand that security issues should be reported privately first
          required: true